sudo: false
language: python

matrix:
  include:
    # Use the built in venv for linux builds
    - os: linux
      sudo: false
      python: "2.7"
    - os: linux
      sudo: false
      python: "3.4"
    - os: linux
      sudo: false
      python: "3.5"
    - os: linux
      sudo: false
      python: "3.6"
    # Travis doesn't have Python 3.7 activated yet
    # - os: linux
    #   sudo: false
    #   python: "3.7"

    # Use generic language for osx
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
        - FSEVENTS_VERSION=1
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
        - FSEVENTS_VERSION=2

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.4
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.4
        - FSEVENTS_VERSION=1
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.4
        - FSEVENTS_VERSION=2

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5
        - FSEVENTS_VERSION=1
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5
        - FSEVENTS_VERSION=2

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6
        - FSEVENTS_VERSION=1
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6
        - FSEVENTS_VERSION=2

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7
        - FSEVENTS_VERSION=1
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7
        - FSEVENTS_VERSION=2

before_install:
  - .travis/install.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source $HOME/miniconda/bin/activate venv; fi
  - pip install --upgrade setuptools
  - pip install coveralls
script:
  - PYTHONPATH=src python setup.py test
after_script:
  - coveralls
